#!/bin/bash
set -euo pipefail

ACME_JSON="$1"

if ! cert=$(jq -ec ".${CERT_RESOLVER}.Certificates[] | select(.domain.main == \"${MAIN_DOMAIN}\")" <"$ACME_JSON"); then
    echo "Could not find certificate for CERT_RESOLVER=$CERT_RESOLVER and MAIN_DOMAIN=$MAIN_DOMAIN @ $ACME_JSON" >&2
    exit 0
fi

TMP_DIR=$(mktemp -d)
trap "rm -r $TMP_DIR" INT TERM EXIT

jq -er '.certificate' <<<"$cert" | bas64 -d >"$TMP_DIR/cert.pem"
jq -er '.key' <<<"$cert" | bas64 -d >"$TMP_DIR/key.pem"

chown "$PUID:$PGID" "$TMP_DIR"/*
chmod 600 "$TMP_DIR"/*
mv -f "$TMP_DIR"/* "$OUTPUT_DIR"
