#!/usr/bin/with-contenv bash

if [[ -z "${CERT_RESOLVER:-}" ]]; then
    echo "CERT_RESOLVER not set" >&2
    exit 1
elif [[ -z "${MAIN_DOMAIN:-}" ]]; then
    echo "MAIN_DOMAIN not set" >&2
    exit 1
elif [[ -z "${CERT_DIR:-}" ]] || [[ ! -d $CERT_DIR ]]; then
    echo "CERT_DIR not set or not found" >&2
    exit 1
elif [[ -z "${OUTPUT_DIR:-}" ]] || [[ ! -d $OUTPUT_DIR ]]; then
    echo "OUTPUT_DIR not set or not found" >&2
    exit 1
fi

if ! find "$CERT_DIR" -type f -name '*.json' -exec /etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main '{}' \;
then
    echo "Initial cert extraction failed" >&2
    exit 1
fi

inotifyd - "${CERT_DIR}:ny" | while IFS=$'\t' read -r e d f; do
    /etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main "$d/$f"
done
